# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json


###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 45a3ba6c4d246cb3c8f650dcdffe4c8157927442

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/54/
Content-Type: application/json
Authorization: Token 45a3ba6c4d246cb3c8f650dcdffe4c8157927442

{
  "status": "DRAFT"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=OPEN
Content-Type: application/json
Authorization: Token eafd203592a9fc874697379fef4937644461dae0

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2024-10-01
Content-Type: application/json

###

# удаление продукта
DELETE {{baseUrl}}/advertisements/45/
Content-Type: application/json
Authorization: Token eafd203592a9fc874697379fef4937644461dae0

###

# добавление в избранное
POST {{baseUrl}}/advertisements/53/add_to_favorite/
Content-Type: application/json
Authorization: Token eafd203592a9fc874697379fef4937644461dae0


###

# показать избранное
GET {{baseUrl}}/advertisements/get_favorite/
Content-Type: application/json
Authorization: Token 45a3ba6c4d246cb3c8f650dcdffe4c8157927442


###