# Generated by Django 4.2.2 on 2023-07-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='creator',
            new_name='User',
        ),
    ]
