# Generated by Django 4.2.2 on 2023-07-05 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_rename_creator_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='advertisements.advertisement'),
        ),
    ]
