# Generated by Django 4.2.2 on 2023-07-11 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("advertisements", "0006_alter_favorite_advertisement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorite",
            old_name="User",
            new_name="user",
        ),
    ]
