# Generated by Django 4.2.3 on 2023-07-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_course_id_alter_course_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
