# Generated by Django 4.2 on 2023-05-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_tag_scope_article_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='scope',
        ),
    ]
